eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10086/eureka/
server:
  port: 8083
spring:
  application:
    name: gateway
# 配置消息转发路由
zuul:
  routes:
    ipfs-service:
      path: /ipfs/**
      serviceId: ipfs-service
      stripPrefix: false
    user-service:
      path: /user/**
      serviceId: user-service
      stripPrefix: false
  prefix: /guardian # 添加统一前缀

  sensitive-headers: Cookie,Set-Cookie,Authorization
  add-host-header: true # 重定向添加Host请求头
